import type { Metadata } from "next";
import { resCartProductType } from "@/types/resTypes";
import { Inter } from "next/font/google";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import LayoutClient from "@/components/LayoutClient";
import StoreProvider from "@/components/StoreProvider";
import { auth } from "./auth";
import userCart from "@/utils/userCart";
import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  const cart = await userCart<resCartProductType>("GET", session?.user?.id);

  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <NavBar session={session} />
          <LayoutClient session={session} cart={cart}>
            {children}
          </LayoutClient>
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
