import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import LayoutClient from "@/components/LayoutClient";
import StoreProvider from "@/components/StoreProvider";
import { auth } from "./auth";
import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <NavBar session={session} />
          <LayoutClient session={session}>{children}</LayoutClient>
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
